[metadata]
name = indico-plugin-payment-eximbay
version = 3.3.0b1
description = Eximbay payments for Indico event registration fees
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8; variant=GFM
url = ""
license = MIT
author = GyuJin Kim (PAL)
author_email = ilyoukim@postech.ac.kr
classifiers =
    Environment :: Plugins
    Environment :: Web Environment
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3.9

[options]
packages = find:
zip_safe = false
include_package_data = true
python_requires = >=3.9.0, <3.13
install_requires =
    indico>=3.2
    indico-plugins>=3.2

[options.entry_points]
indico.plugins =
    payment_eximbay = indico_payment_eximbay.plugin:EximbayPaymentPlugin

